'''
Constants.py
'''
#RESOURCES
TASK_CPU = 0.2
TASK_MEM = 32
EXECUTOR_CPUS = 1
EXECUTOR_MEM = 32
#HASH KEY SUFIX
BLANK = ''
CONTAINER_KEY_TAG = ':container'
SOURCE_KEY_TAG = ':source'
STATE_KEY_TAG = ':state'
AGENT_KEY_TAG = ':agent'

#CONSTANTS MINIMAL SCHEDULER
REDIS_TASKS_SET = "tasks"
REDIS_FW_ID='fwk_id'
REDIS_RECONCILE='reconcile'

#CONSTANTS MESSAGES.PROTO
PROTO_TASK_ID={'task_id':{'value':'%s'}}
#PROTO_TASK_ID='task_id'
#PROTO_VALUE='value'